### ISSUE TITLE
S3 bucket not working in-game

### ISSUE THREAD

**Issue by Shadylbx** [CounterHack/HolidayHack2020#15] opened 2020-12-13 19:09 UTC
previously modified the wordlist with the name of the bucket, all lower and it was working for me.  The in Game can no longer find bucket, but I can access it directly from local browser.

**Comment by Shadylbx** [comment] 2020-12-13 19:10
![bucket no found](https://user-images.githubusercontent.com/8661655/102021302-ed1f6a80-3d4c-11eb-8db7-db56a2f0a366.jpg)

**Comment by tkh16** [comment] 2020-12-13 20:48
Closing this as a duplicate of #16.  Thanks for the report; we're looking into the issue.

**Closed as completed by tkh16** 2020-12-13 20:48 UTC
