### ISSUE TITLE
Game not working at url http://kringlecon.com

### ISSUE THREAD

**Issue by wcmoody** [CounterHack/HolidayHack2020#7] opened 2020-12-10 16:29 UTC
When you access the game via the url https://kringlecon.com, you get a mix of 2019 and 2020. You get the holly background from 2019, but the frosted over login prompt from 2020.

<img width="942" alt="Screen Shot 2020-12-10 at 11 28 37 AM" src="https://user-images.githubusercontent.com/632400/101800118-e8ec1680-3ada-11eb-8b74-b366e32e1b08.png">

Then when you log in you are stuck in a game with the 2019 holly background. I think this is level -1 of Kringlecon. Thanks

<img width="346" alt="Screen Shot 2020-12-10 at 11 25 23 AM" src="https://user-images.githubusercontent.com/632400/101800179-fdc8aa00-3ada-11eb-88e6-d0dd640ce48d.png">

**Comment by wcmoody** [comment] 2020-12-10 16:37
This is on windows 10 pro with Chrome, btw. I don't see it on Chrome on MacOS 10.14.6

**Comment by dpendolino** [comment] 2020-12-10 16:38
@wcmoody Can you try a hard refresh? I just tried it on Chrome in Linux and got the correct version of the game.

**Comment by tkh16** [comment] 2020-12-10 22:36
Yeah, I can't reproduce this issue either, and suspect it to be a local caching issue?

**Comment by drsh0** [comment] 2020-12-11 06:30
I didn't have this particular issue but disabling ad blocking extensions (ublock origin in my case, firefox) for 2020.kringlecon.com and kringlecon.com fixed any issues I was having.

**Comment by dpendolino** [comment] 2020-12-13 00:55
@wcmoody has this happened again? I'm going to close this out unless anyone else can reproduce it. Thanks!

**Comment by dpendolino** [comment] 2020-12-14 18:04
Closing for now, until we get another report.

**Closed as completed by dpendolino** 2020-12-14 18:04 UTC
